import React from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { Icon } from '../Icon';
import { URLAnalysisResult } from '../../types';
import { UrlPdfReportTemplate } from '../UrlPdfReportTemplate';

interface UrlResultScreenProps {
    url: string;
    result: URLAnalysisResult;
    onBack: () => void;
    onAnalyzeAnother: () => void;
}

export const UrlResultScreen: React.FC<UrlResultScreenProps> = ({
    url,
    result,
    onBack,
    onAnalyzeAnother
}) => {
    // Derived booleans for UI logic
    const hasHttps = result.https_status === "Valid";
    const isIpBased = result.analysis_metric.domain_structure === "IP-Based Detection";
    const suspiciousTLD = result.analysis_metric.tld_analysis === "Suspicious Extension";
    const hasPhishingKeywords = result.analysis_metric.phishing_keywords === "Detected";
    // Heuristic for subdomains if not provided directly
    const tooManySubdomains = result.analysis_metric.subdomain_count > 2;

    // Helper for classification color
    const getClassificationColor = () => {
        switch (result.verdict) {
            case 'SAFE':
                return {
                    bg: 'bg-green-50',
                    border: 'border-green-200',
                    text: 'text-green-700',
                    icon: 'text-green-600',
                    badge: 'bg-green-100 text-green-700'
                };
            case 'MALICIOUS':
                return {
                    bg: 'bg-red-50',
                    border: 'border-red-200',
                    text: 'text-red-700',
                    icon: 'text-red-600',
                    badge: 'bg-red-100 text-red-700'
                };
            default: // Handle unknown or 'Suspicious' if it ever appears
                return {
                    bg: 'bg-yellow-50',
                    border: 'border-yellow-200',
                    text: 'text-yellow-700',
                    icon: 'text-yellow-600',
                    badge: 'bg-yellow-100 text-yellow-700'
                };
        }
    };

    const getClassificationIcon = () => {
        switch (result.verdict) {
            case 'SAFE':
                return 'check_circle';
            case 'MALICIOUS':
                return 'dangerous';
            default:
                return 'warning';
        }
    };

    const colors = getClassificationColor();

    const generatePdfReport = async () => {
        const element = document.getElementById('pdf-report-template-url') as HTMLElement;

        if (!element) return;

        try {
            const canvas = await html2canvas(element, {
                scale: 2,
                logging: false,
                useCORS: true,
                allowTaint: true
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4',
                compress: true
            });

            const imgWidth = 210; // A4 width in mm
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            // Add only single page
            pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);

            const caseId = `URL-${Date.now()}`;
            pdf.save(`deepcheck-url-report-${caseId}.pdf`);
        } catch (err) {
            console.error('Error generating PDF:', err);
            alert('Failed to generate PDF report');
        }
    };

    const shareReport = async () => {
        const reportText = `
DeepCheck URL Security Audit Report

URL: ${url}
Classification: ${result.verdict}
Risk Score: ${result.confidence_score}/100

${result.threat_message}
Recommendation: ${result.recommendation}

Technical Details:
- Protocol: ${result.analysis_metric.protocol_check}
- HTTPS: ${hasHttps ? 'Yes' : 'No'}
- IP-Based: ${isIpBased ? 'Yes' : 'No'}
- Suspicious TLD: ${suspiciousTLD ? 'Yes' : 'No'}
- Subdomains: ${result.analysis_metric.subdomain_count}

Generated by DeepCheck - Advanced Security Analysis Tool
        `.trim();

        const whatsappText = `🔒 *DeepCheck URL Security Audit*

🔗 *URL:* ${url}
📊 *Classification:* ${result.verdict}
⚠️ *Risk Score:* ${result.confidence_score}/100

📝 *Assessment:*
${result.threat_message}
${result.recommendation}

🔧 *Technical Findings:*
• Protocol: ${result.analysis_metric.protocol_check}
• HTTPS: ${hasHttps ? '✅ Secure' : '❌ Insecure'}
• IP-Based: ${isIpBased ? '⚠️ Yes' : '✅ No'}
• Suspicious TLD: ${suspiciousTLD ? '⚠️ Detected' : '✅ None'}
• Subdomains: ${result.analysis_metric.subdomain_count}

Generated by DeepCheck - Advanced Security Analysis Tool`;

        // Create a share menu
        const shareOptions = document.createElement('div');
        shareOptions.style.cssText = `
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background: white;
            border-radius: 16px;
            padding: 24px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            z-index: 1000;
            min-width: 350px;
            max-height: 80vh;
            overflow-y: auto;
        `;

        shareOptions.innerHTML = `
            <div style="margin-bottom: 20px;">
                <h3 style="margin: 0 0 16px 0; font-size: 18px; font-weight: bold; color: #333;">Share Report</h3>
            </div>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px;">
                <button id="share-whatsapp" style="padding: 16px 12px; background: linear-gradient(135deg, #25D366, #128C7E); color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 13px; display: flex; flex-direction: column; align-items: center; gap: 8px; transition: transform 0.2s;">
                    💬
                    <span>WhatsApp</span>
                </button>
                <button id="share-telegram" style="padding: 16px 12px; background: linear-gradient(135deg, #0088cc, #005ba0); color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 13px; display: flex; flex-direction: column; align-items: center; gap: 8px; transition: transform 0.2s;">
                    ✈️
                    <span>Telegram</span>
                </button>
                <button id="share-email" style="padding: 16px 12px; background: linear-gradient(135deg, #EA4335, #C5221F); color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 13px; display: flex; flex-direction: column; align-items: center; gap: 8px; transition: transform 0.2s;">
                    📧
                    <span>Email</span>
                </button>
                <button id="share-twitter" style="padding: 16px 12px; background: linear-gradient(135deg, #1DA1F2, #1a8cd8); color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 13px; display: flex; flex-direction: column; align-items: center; gap: 8px; transition: transform 0.2s;">
                    𝕏
                    <span>Twitter</span>
                </button>
                <button id="share-facebook" style="padding: 16px 12px; background: linear-gradient(135deg, #1877F2, #0a66c2); color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 13px; display: flex; flex-direction: column; align-items: center; gap: 8px; transition: transform 0.2s;">
                    👍
                    <span>Facebook</span>
                </button>
                <button id="share-copy" style="padding: 16px 12px; background: linear-gradient(135deg, #6B7280, #4B5563); color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 13px; display: flex; flex-direction: column; align-items: center; gap: 8px; transition: transform 0.2s;">
                    📋
                    <span>Copy Text</span>
                </button>
            </div>
            <button id="share-native" style="width: 100%; padding: 12px 16px; background: #7C3AED; color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 14px; margin-bottom: 8px;">
                📤 More Options
            </button>
            <button id="share-close" style="width: 100%; padding: 12px 16px; background: #E5E7EB; color: #333; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 14px;">
                Close
            </button>
        `;

        document.body.appendChild(shareOptions);

        // Add backdrop
        const backdrop = document.createElement('div');
        backdrop.style.cssText = `
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(0,0,0,0.5);
            z-index: 999;
        `;
        document.body.appendChild(backdrop);

        const removeMenu = () => {
            shareOptions.remove();
            backdrop.remove();
        };

        // WhatsApp
        document.getElementById('share-whatsapp')?.addEventListener('click', () => {
            const whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(whatsappText)}`;
            window.open(whatsappUrl, '_blank');
            removeMenu();
        });

        // Telegram
        document.getElementById('share-telegram')?.addEventListener('click', () => {
            const telegramUrl = `https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(`URL Security Report: ${result.verdict}`)}`;
            window.open(telegramUrl, '_blank');
            removeMenu();
        });

        // Email
        document.getElementById('share-email')?.addEventListener('click', () => {
            const emailBody = encodeURIComponent(reportText);
            window.location.href = `mailto:?subject=DeepCheck URL Security Report&body=${emailBody}`;
            removeMenu();
        });

        // Twitter
        document.getElementById('share-twitter')?.addEventListener('click', () => {
            const twitterText = `🔒 Just analyzed a URL with DeepCheck:\n${url}\n📊 Classification: ${result.verdict}\n⚠️ Risk Score: ${result.confidence_score}/100\n\n#Security #DeepCheck`;
            const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(twitterText)}`;
            window.open(twitterUrl, '_blank');
            removeMenu();
        });

        // Facebook
        document.getElementById('share-facebook')?.addEventListener('click', () => {
            const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}&quote=${encodeURIComponent(`DeepCheck URL Security Report: ${result.verdict}`)}`;
            window.open(facebookUrl, '_blank');
            removeMenu();
        });

        // Copy to Clipboard
        document.getElementById('share-copy')?.addEventListener('click', () => {
            navigator.clipboard.writeText(reportText).then(() => {
                alert('Report copied to clipboard!');
                removeMenu();
            });
        });

        // Native Share
        document.getElementById('share-native')?.addEventListener('click', async () => {
            if (navigator.share) {
                try {
                    await navigator.share({
                        title: 'DeepCheck URL Security Report',
                        text: reportText,
                    });
                } catch (err) {
                    console.log('Share cancelled or failed:', err);
                }
            } else {
                alert('Sharing not supported on this device');
            }
            removeMenu();
        });

        document.getElementById('share-close')?.addEventListener('click', removeMenu);
        backdrop.addEventListener('click', removeMenu);

        // Add hover effects
        const buttons = shareOptions.querySelectorAll('button[id^="share-"]:not(#share-native):not(#share-close)');
        buttons.forEach(el => {
            const btn = el as HTMLElement;
            btn.addEventListener('mouseenter', () => {
                btn.style.transform = 'scale(1.05)';
            });
            btn.addEventListener('mouseleave', () => {
                btn.style.transform = 'scale(1)';
            });
        });
    };

    return (
        <div className="h-full w-full bg-white flex flex-col relative overflow-hidden">
            {/* Top Navigation */}
            <div className="w-full px-6 pt-12 pb-2 flex justify-start shrink-0 z-20">
                <button
                    onClick={onBack}
                    className="text-slate-500 hover:text-slate-800 transition-colors p-2 rounded-full hover:bg-slate-100 -ml-2"
                    aria-label="Back"
                >
                    <Icon name="arrow_back" className="text-2xl" />
                </button>
            </div>

            {/* Verdict Header (Fixed/Static at top) */}
            <div className="w-full px-6 pb-2 flex flex-col items-center shrink-0 z-10 bg-white shadow-sm relative">
                <div className="flex flex-col items-center justify-center gap-3 mb-3 mt-1 w-full text-center">
                    {/* Compact Icon */}
                    <div className="relative w-16 h-16 shrink-0">
                        <div className="w-full h-full rounded-2xl overflow-hidden shadow-sm bg-slate-50 flex items-center justify-center">
                            <Icon name="link" className={`text-3xl ${colors.icon}`} />
                        </div>
                    </div>

                    {/* Verdict Text */}
                    <h1 className={`text-3xl font-[800] tracking-tight ${colors.text} uppercase`}>
                        {result.verdict}
                    </h1>
                </div>

                {/* Confidence Bar */}
                <div className="w-full max-w-sm flex flex-col items-center mb-3">
                    <div className="w-full flex justify-between text-xs font-bold uppercase tracking-wider mb-1 px-1 opacity-70">
                        <span>Confidence Score</span>
                        <span>{result.confidence_score}%</span>
                    </div>
                    <div className="w-full h-1.5 bg-slate-100 rounded-full overflow-hidden">
                        <div
                            className={`h-full ${colors.text.includes('green') ? 'bg-green-500' : colors.text.includes('yellow') ? 'bg-yellow-500' : 'bg-red-500'} rounded-full transition-all duration-500`}
                            style={{ width: `${result.confidence_score}%` }}
                        ></div>
                    </div>
                </div>
            </div>

            {/* Scrollable Technical Details */}
            <div className="flex-1 w-full overflow-y-auto px-6 py-4 bg-slate-50/50">
                <div className="w-full max-w-2xl mx-auto flex flex-col gap-6">



                    {/* Technical Summary Cards */}
                    <div className="space-y-3">
                        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider ml-1">Analysis Metrics</h3>
                        <div className="bg-white border border-slate-100 rounded-lg p-3 flex items-center justify-between shadow-sm">
                            <div className="flex items-center gap-3">
                                <Icon name="check_circle" className={`text-lg ${colors.icon}`} />
                                <span className="text-slate-700 font-medium text-sm">Protocol</span>
                            </div>
                            <span className={`${colors.text} font-semibold text-sm`}>{result.protocol}</span>
                        </div>
                        <div className="bg-white border border-slate-100 rounded-lg p-3 flex items-center justify-between shadow-sm">
                            <div className="flex items-center gap-3">
                                <Icon name={hasHttps ? "check_circle" : "dangerous"} className={`text-lg ${hasHttps ? 'text-green-600' : 'text-red-600'}`} />
                                <span className="text-slate-700 font-medium text-sm">HTTPS</span>
                            </div>
                            <span className={`${hasHttps ? 'text-green-600' : 'text-red-600'} font-semibold text-sm`}>
                                {result.https_status}
                            </span>
                        </div>
                    </div>

                    {/* Explanation */}
                    <div className="space-y-2">
                        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider ml-1">Security Assessment</h3>
                        <div className="bg-white border border-slate-100 rounded-lg p-3 flex items-center gap-3 shadow-sm">
                            <div className={`w-10 h-10 rounded-lg ${colors.bg} flex items-center justify-center shrink-0`}>
                                <Icon name={result.verdict === 'SAFE' ? 'check_circle' : 'dangerous'} className={`text-xl ${colors.icon}`} />
                            </div>
                            <div className="flex-1">
                                <p className={`${colors.text} font-semibold text-sm`}>
                                    {result.threat_message}
                                </p>
                                <p className="text-slate-500 text-xs">
                                    {result.recommendation}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Bottom Action Bar - Fixed */}
            <div className="shrink-0 w-full bg-white border-t border-slate-200 px-6 py-4 pb-8 flex flex-col gap-3 shadow-[0_-4px_20px_rgba(0,0,0,0.05)] z-20">
                <button
                    onClick={generatePdfReport}
                    className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-3.5 px-6 rounded-full transition-all duration-300 hover:shadow-lg active:scale-95 flex items-center justify-center gap-2"
                >
                    <Icon name="download" className="text-lg" />
                    <span>DOWNLOAD REPORT</span>
                </button>
                <button
                    onClick={onAnalyzeAnother}
                    className="w-full text-slate-500 font-semibold py-2 hover:text-slate-800 transition-colors uppercase text-sm tracking-wide"
                >
                    Analyze Another URL
                </button>
            </div>

            {/* Hidden PDF Template */}
            <UrlPdfReportTemplate url={url} result={result} date={new Date().toLocaleDateString('en-US', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })} />
        </div >
    );
};

// Helper component for technical details
interface DetailItemProps {
    label: string;
    value: string;
    status: 'good' | 'bad' | 'neutral';
}

const DetailItem: React.FC<DetailItemProps> = ({ label, value, status }) => {
    const getStatusColor = () => {
        switch (status) {
            case 'good':
                return 'text-green-600';
            case 'bad':
                return 'text-red-600';
            case 'neutral':
                return 'text-slate-600';
        }
    };

    return (
        <div className="flex flex-col gap-1">
            <p className="text-xs text-slate-500 uppercase tracking-wider">
                {label}
            </p>
            <p className={`text-sm font-semibold ${getStatusColor()}`}>
                {value}
            </p>
        </div>
    );
};
